### ISSUE TITLE
Vibhakti Vachana of Padaccheda in 1/2/57

### ISSUE THREAD

**Issue by chaitanya-lakkundi** [ashtadhyayi-com/data#12]
Namaste.

In सूत्रच्छेदः of [कालोपसर्जने च तुल्यम्](https://ashtadhyayi.com/sutraani/1/2/57) , काल-उपसर्जने **प्रथमा-द्विवचनम्** is mentioned.

However, in बालमनोरमा , कालश्च उपसर्जनं चेति **समाहारद्वन्द्वाद्विषयसप्तमी** is given.

I am not sure if any special explanation is required to arrive at प्रथमा-द्विवचनम् .
Kindly verify the विभक्तिः and वचनम् . @neeleshb 

File which contains सूत्रच्छेदः = [https://github.com/ashtadhyayi-com/data/blob/master/sutraani/data.txt](https://github.com/ashtadhyayi-com/data/blob/master/sutraani/data.txt)

"i": "12057"
"pc": "काल-उपसर्जने$S$1$2$##च$S$0$0$##तुल्यम्$S$1$1$"

Chaitanya

**Comment by neeleshb** [comment]
https://github.com/ashtadhyayi-com/data/commit/bc26856b282048fa8ec0ed0f691c93b180c34d64
