### ISSUE TITLE
Can we include Sutra "type" ?

### ISSUE THREAD

**Issue by hrishikeshrt** [ashtadhyayi-com/data#20]
Dr. Pushpa Dikshit's book mentions which are संज्ञासूत्राणि, परिभाषासूत्राणि, अतिदेशसूत्राणि, अधिकारसूत्राणि 
The remaining सूत्राणि would be either विधि or नियम।
I have extracted the list of sutras from each of the 4 types mentioned, and if this proposal is acceptable can send a PR with the info added as a "type" field to sutraani files. It can also be displayed in the front-end display of each sutra.

**Comment by neeleshb** [comment]
Somebody else already prepared this data which is pending with me for quite
some time. Please write to me separately and I will let you know how to
incorporate this data into the system.
