### ISSUE TITLE
अण् प्रत्याहार - Clarification needed

### ISSUE THREAD

**Issue by sudheerays123** [ashtadhyayi-com/data#23]
Namaste , 

There are two अण् in प्रत्याहार list and the latter one should only be used in the सूत्र - अणुदित् सवर्णस्य चाप्रत्ययः , so it would be good if you can mention this so that it beside the सूत्र clarifies the doubts 
Thanks

**Comment by neeleshb** [comment]
This has been mentioned at appropriate places, please see
https://ashtadhyayi.com/shivasutra/#id=6, also in अणुदित्सवर्णस्य sutra.

For any further clarification / questions, please write to me directly.
