### ISSUE TITLE
Inconsistent spelling in sutras २.४.५१ & ६.१.३१

### ISSUE THREAD

**Issue by vipranarayan14** [ashtadhyayi-com/data#293]
The spelling of संश्चङोः is not consistent between the sutras:

<img width="852" alt="Screenshot 2024-05-09 at 11 07 35 AM" src="https://github.com/ashtadhyayi-com/data/assets/17687018/e780f6cb-c678-4693-bf34-274e33721437">

(I searched for one, but was taken to another and didn't expect that commentary.)

**Comment by neeleshb** [comment]
Thanks, fixed by https://github.com/ashtadhyayi-com/data/commit/666226b2f72459b3976476fb2b152d3dde438fea

**Comment by vipranarayan14** [comment]
👍 Thanks
