### ISSUE TITLE
Adhikara Error? or Intentional?

### ISSUE THREAD

**Issue by hrishikeshrt** [ashtadhyayi-com/data#60]
Starting from 1.3.73, in अधिकार, there's `आत्मनेपदम् 1/1` appearing. Is that `1/1` intentional? If so, what does that signify? (if not, I can modify and send in a pull request).
Further, the अधिकार is originating from 1.3.12, then should it not be present from 1.3.13 itself? It does not appear before 1.3.73.
Is this also an error or is it intentional?

**Comment by neeleshb** [comment]
"आत्मनेपदम्" is technically an anuvrutti rather than a separate adhikaar,
and it has been represented as anuvrutti.
you can remove the entire "ad" value for 1.3.73 and others (I think the
mistake goes for 4-5 more sutras)
