### ISSUE TITLE
हविस् or हविष् ?

### ISSUE THREAD

**Issue by hrishikeshrt** [ashtadhyayi-com/data#72]
https://ashtadhyayi.com/shabda/79.002

I believe the praatipadika should be हविस् and not हविष्  and ष् comes in the inflections due to https://ashtadhyayi.com/sutraani/8/3/58

Please correct me if I am wrong.

**Comment by neeleshb** [comment]
That is correct, technically all the षकारान्त pratipadikas should be
सकारान्त. But people commonly search / look for the षकारान्त version, so I
populated all these with ष् at the end. (Eg. आशिष्, धनुष् , पिपठिष् etc)

I am yet to clean up the shabdapatha data. I will do some kind of fix there
(like, add another entry called original_pratipadik etc). I haven't given
much thought to it yet.
