### ISSUE TITLE
पाशुपतम् उत पाशुपत्यम्

### ISSUE THREAD

**Issue by chaitanya-lakkundi** [ashtadhyayi-com/data#75]
@neeleshb श्रीमन्, [4.2.24 सास्य देवता](https://www.ashtadhyayi.com/sutraani/4/2/24) इति सूत्रस्य सूत्रार्थे, पाशुपत्य इति लिखितमस्ति । परन्तु तत्रैव सिद्धान्तकौमुद्याम् पाशुपतम् इति रूपं प्रकाशितम् । 

[दित्यदित्यादित्यपत्युत्तरपदाण्ण्यः](https://www.ashtadhyayi.com/sutraani/4/1/85) इति सूत्रबलात् पत्युत्तरपद-शब्दानामपि ण्यप्रत्ययः सिद्ध्यति । तथापि केनचित् कारणेन कौमुद्यां पाशुपत्यमिति नोदाहृतम् । अतः शुद्धरूपं किमिति शङ्के ।

**Comment by neeleshb** [comment]
पाशुपतमित्येव स्यात्, [अश्वपत्यादिगणे](https://ashtadhyayi.com/sutraani/4/1/84) तस्य परिगणनात् ।

**Comment by chaitanya-lakkundi** [comment]
स्पष्टं तत्तर्हि । 3100e018f8639911b053d3500a7a0ab5c358d162
