### ISSUE TITLE
8.3.45

### ISSUE THREAD

**Issue by hrishikeshrt** [ashtadhyayi-com/data#85]
In the English meaning,

>  While doing a समास, the विसर्ग of the इस्/उस्-प्रत्यय when followed by a letter from कवर्ग or पवर्ग is **optionally** converted to a षकार whenever the words involved in the समास are associated with each other. However, if the पूर्वपद of this समास is a समास on its own, then the षत्व is completely prohibited.

Is "optionally" correct?
The meaning in Sanskrit says षत्व is नित्यम्।

**Comment by neeleshb** [comment]
That is correct. Fixed.
